spring:

  application:
    name: vetclinic

  thymeleaf:
    check-template-location: false
    prefix: classpath:/templates/pdf/
    suffix: .html
    mode: HTML
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/vetapp
    username: vetapp_user
    password: vetapp_pass
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 3
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Europe/Belgrade
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_EMAIL_USERNAME
    password: YOUR_EMAIL_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

app:
  jwt:
    secret: dkFsaWRWZXRDbGluaWNTZWN1cml0eUtleTIwMjZGZWJydWFyeQ==
    access-token-expiration: 1800000
    refresh-token-expiration: 604800000
  upload:
    base-dir: uploads
  cors:
    allowed-origins: http://localhost:3000
  sms:
    twilio:
      account-sid: YOUR_TWILIO_ACCOUNT_SID
      auth-token: YOUR_TWILIO_AUTH_TOKEN
      from-number: "+447886066323"
      enabled: false
  email:
    from: YOUR_EMAIL_FROM
    enabled: false
    resend:
      api-key: YOUR_RESEND_API_KEY

# SpringDoc / Swagger UI
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
    default-models-expand-depth: 1
logging:
  file:
   name: logs/vetclinic.log
  level:
   com.softart.vetclinic: DEBUG

