ALTER TABLE service DROP CONSTRAINT IF EXISTS service_category_check;

ALTER TABLE service ADD CONSTRAINT service_category_check
    CHECK (category IN (
        'EXAMINATION', 'MEDICATION_APPLICATION', 'ANESTHESIA', 'LAB', 'ULTRASOUND',
        'REPRODUCTION', 'STERILIZATION', 'SURGERY', 'GROOMING', 'PREVENTIVE',
        'VACCINATION', 'DENTAL', 'THERAPY', 'EUTHANASIA', 'OTHER'
    ));